# Generated by Django 4.2 on 2023-04-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=64)),
                ('_last_update', models.DateTimeField(auto_now=True)),
                ('_weather', models.CharField(blank=True, max_length=64, null=True)),
                ('_temperature', models.FloatField(blank=True, null=True)),
                ('_humidity', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
