version: "3.8"

services:
  django:
    build: .
    volumes:
      - .:/django
      - static:/django/root/staticfiles
    ports:
      - "8000:8000"
    expose:
      - 8000
    container_name: django

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - django
      - certbot
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    volumes:
      - static:/var/www/html/static/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    command: certonly --standalone --webroot-path=/var/www/html
      --email aufrutten@gmail.com --agree-tos --no-eff-email
      -d aufrutten.com

volumes:
  static:
  www-html:
  etc-letsencrypt:
