version: "3.8"

services:
  django:
    build: .
    volumes:
      - .:/django
      - static:/django/root/staticfiles
    ports:
      - "8000:8000"
    expose:
      - 8000
    container_name: django
    command: ./start

  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/var/www/html/static/
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  static: