version: "3.8"

services:
  django:
    build: .
    volumes:
      - .:/django
      - static:/django/root/staticfiles
    expose:
      - 8000
    container_name: django

  nginx_http:
    container_name: nginx_http
    image: nginx:latest
    depends_on:
      django:
        condition: service_started
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - static:/var/www/html/static/
      - ./nginx/dev/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  static:
